import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { 
  LayoutDashboard, Video, Bell, FileText, User, LogOut, 
  Menu, X, Camera, Shield, AlertTriangle, Users, Flame,
  Download, ChevronDown, Home, Edit
} from 'lucide-react';
import { 
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, 
  ResponsiveContainer, PieChart, Pie, Cell, Legend 
} from 'recharts';

const Reports = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [activeTab, setActiveTab] = useState('Daily');
  
  // ✅ NEW: Dropdown state and user data
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [userData, setUserData] = useState(null);
  const dropdownRef = useRef(null);
  
  // Dynamic state
  const [reports, setReports] = useState([]);
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);

  // Fetch reports and alerts for this user
  useEffect(() => {
    const fetchData = async () => {
      try {
        const token = localStorage.getItem('token');
        const storedUser = JSON.parse(localStorage.getItem('user'));
        
        if (!storedUser?.id) {
          setLoading(false);
          return;
        }
        
        const headers = { 'Authorization': `Bearer ${token}` };
        
        // Fetch reports generated by this user
        const reportsRes = await fetch('http://localhost:5000/api/reports', { headers });
        const reportsResult = await reportsRes.json();
        
        // Fetch cameras assigned to this user
        const camerasRes = await fetch(`http://localhost:5000/api/users/${storedUser.id}/cameras`, { headers });
        const camerasResult = await camerasRes.json();
        
        let userAlerts = [];
        if (camerasResult.success && camerasResult.data.length > 0) {
          const cameraIds = camerasResult.data.map(c => c.id);
          const alertsRes = await fetch('http://localhost:5000/api/alerts', { headers });
          const alertsResult = await alertsRes.json();
          
          if (alertsResult.success) {
            userAlerts = alertsResult.data.filter(a => cameraIds.includes(a.camera_id));
          }
        }
        
        if (reportsResult.success) {
          // Filter reports for this user only
          const userReports = reportsResult.data.filter(r => r.generated_by === storedUser.id);
          setReports(userReports);
        }
        
        setAlerts(userAlerts);
      } catch (error) {
        console.error("Failed to fetch reports data:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  // ✅ Fetch user data for header dropdown
  useEffect(() => {
    const fetchUserData = async () => {
      try {
        const token = localStorage.getItem('token');
        const storedUser = JSON.parse(localStorage.getItem('user'));
        
        if (!storedUser?.id) return;
        
        const response = await fetch(`http://localhost:5000/api/users/${storedUser.id}`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        const result = await response.json();
        
        if (result.success) {
          setUserData(result.data);
        }
      } catch (error) {
        console.error("Failed to fetch user data:", error);
      }
    };
    fetchUserData();
  }, []);

  // ✅ Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setDropdownOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Calculate dynamic stats from alerts
  const totalAlerts = alerts.length;
  const intrusions = alerts.filter(a => a.threat_type?.toLowerCase().includes('intrusion')).length;
  const unknownFaces = alerts.filter(a => a.threat_type?.toLowerCase().includes('face')).length;
  const fireAlerts = alerts.filter(a => a.threat_type?.toLowerCase().includes('fire')).length;
  const crowdAlerts = alerts.filter(a => a.threat_type?.toLowerCase().includes('crowd')).length;
  
  const highPriority = alerts.filter(a => a.priority === 'high' || a.priority === 'critical').length;
  const mediumPriority = alerts.filter(a => a.priority === 'medium').length;
  const lowPriority = alerts.filter(a => a.priority === 'low').length;
  const resolvedAlerts = alerts.filter(a => a.status === 'resolved' || a.status === 'closed').length;

  // Dynamic chart data with safe fallbacks
  const alertData = alerts.length > 0 
    ? [
        { time: '00:00', alerts: Math.floor(Math.random() * 5) },
        { time: '04:00', alerts: Math.floor(Math.random() * 5) },
        { time: '08:00', alerts: Math.floor(Math.random() * 8) },
        { time: '12:00', alerts: totalAlerts },
        { time: '16:00', alerts: Math.floor(Math.random() * 6) },
        { time: '20:00', alerts: Math.floor(Math.random() * 4) },
        { time: '24:00', alerts: Math.floor(Math.random() * 3) }
      ]
    : [
        { time: '00:00', alerts: 0 },
        { time: '04:00', alerts: 0 },
        { time: '08:00', alerts: 0 },
        { time: '12:00', alerts: 0 },
        { time: '16:00', alerts: 0 },
        { time: '20:00', alerts: 0 },
        { time: '24:00', alerts: 0 }
      ];

  const threatData = alerts.length > 0
    ? [
        { name: 'Intrusion', value: intrusions || 1, color: '#6366f1' },
        { name: 'Unknown Face', value: unknownFaces || 1, color: '#3b82f6' },
        { name: 'Fire', value: fireAlerts || 1, color: '#ef4444' },
        { name: 'Crowd', value: crowdAlerts || 1, color: '#f59e0b' },
        { name: 'Other', value: (totalAlerts - intrusions - unknownFaces - fireAlerts - crowdAlerts) || 1, color: '#6b7280' },
      ]
    : [
        { name: 'No Data', value: 100, color: '#334155' },
      ];

  // Dynamic recent reports
  const recentReports = reports.length > 0
    ? reports.slice(0, 3).map(r => ({
        title: r.report_name || `${r.report_type} Report`,
        date: `Generated on ${new Date(r.created_at).toLocaleString()}`
      }))
    : [];

  const navItems = [
    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/user/dashboard' },
    { id: 'monitoring', label: 'Live Monitoring', icon: Video, path: '/user/monitoring' },
    { id: 'alerts', label: 'Alerts', icon: Bell, badge: totalAlerts, path: '/user/alerts' },
    { id: 'reports', label: 'Reports', icon: FileText, path: '/user/reports', active: true },
    { id: 'profile', label: 'Profile', icon: User, path: '/user/profile' },
  ];

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0a1120] flex items-center justify-center text-white">
        <div className="text-xl font-semibold animate-pulse">Loading Reports...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0a1120] text-white">
      {/* Header */}
      <header className="bg-[#0f172a] border-b border-white/10 sticky top-0 z-50">
        <div className="flex items-center justify-between px-6 py-4">
          <div className="flex items-center space-x-4">
            <button onClick={() => setSidebarOpen(!sidebarOpen)} className="p-2 hover:bg-white/5 rounded-lg transition-colors">
              {sidebarOpen ? <X size={24} /> : <Menu size={24} />}
            </button>
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-emerald-500/20 rounded-lg flex items-center justify-center">
                <Shield className="text-emerald-400" size={24} />
              </div>
              <div>
                <h1 className="text-lg font-bold tracking-wide">AI SURVEILLANCE</h1>
                <p className="text-xs text-gray-400">Smart Security System</p>
              </div>
            </div>
          </div>
          <div className="flex items-center space-x-4">
            <button className="relative p-2 hover:bg-white/5 rounded-lg transition-colors">
              <Bell size={20} />
              {totalAlerts > 0 && (
                <span className="absolute -top-1 -right-1 w-5 h-5 bg-red-500 text-xs rounded-full flex items-center justify-center">
                  {totalAlerts}
                </span>
              )}
            </button>
            
            {/* ✅ UPDATED: Dropdown Menu */}
            <div className="relative" ref={dropdownRef}>
              <button 
                onClick={() => setDropdownOpen(!dropdownOpen)}
                className="flex items-center space-x-3 pl-6 border-l border-white/10 cursor-pointer hover:bg-white/5 rounded-lg p-2 transition-colors"
              >
                <div className="w-10 h-10 rounded-full overflow-hidden bg-gradient-to-br from-purple-500 to-pink-600 flex items-center justify-center">
                  {userData?.profile_photo ? (
                    <img src={userData.profile_photo} alt={userData.full_name} className="w-full h-full object-cover" />
                  ) : (
                    <User size={20} className="text-white" />
                  )}
                </div>
                <div className="hidden md:block text-right">
                  <p className="text-sm font-medium">{userData?.full_name || 'Security Guard'}</p>
                  <p className="text-xs text-gray-400">User</p>
                </div>
                <ChevronDown size={16} className={`text-gray-400 transition-transform ${dropdownOpen ? 'rotate-180' : ''}`} />
              </button>

              {/* Dropdown Menu */}
              {dropdownOpen && (
                <div className="absolute right-0 mt-2 w-56 bg-[#0f172a] border border-white/10 rounded-xl shadow-2xl overflow-hidden z-50 animate-fadeIn">
                  <style>{`
                    @keyframes fadeIn {
                      from { opacity: 0; transform: translateY(-10px); }
                      to { opacity: 1; transform: translateY(0); }
                    }
                    .animate-fadeIn { animation: fadeIn 0.2s ease-out; }
                  `}</style>
                  
                  <div className="p-4 border-b border-white/10 bg-gradient-to-br from-purple-500/10 to-pink-500/10">
                    <p className="text-sm font-semibold text-white">{userData?.full_name || 'Security Guard'}</p>
                    <p className="text-xs text-gray-400 truncate">{userData?.email || 'user@example.com'}</p>
                  </div>

                  <div className="py-2">
                    <button 
                      onClick={() => { setDropdownOpen(false); navigate('/user/dashboard'); }}
                      className="w-full flex items-center space-x-3 px-4 py-2.5 text-sm text-gray-300 hover:bg-white/5 hover:text-white transition-colors"
                    >
                      <LayoutDashboard size={16} className="text-purple-400" />
                      <span>Dashboard</span>
                    </button>
                    <button 
                      onClick={() => { setDropdownOpen(false); navigate('/user/dashboard'); }}
                      className="w-full flex items-center space-x-3 px-4 py-2.5 text-sm text-gray-300 hover:bg-white/5 hover:text-white transition-colors"
                    >
                      <Home size={16} className="text-purple-400" />
                      <span>Home</span>
                    </button>
                    <button 
                      onClick={() => { setDropdownOpen(false); navigate('/user/edit-profile'); }}
                      className="w-full flex items-center space-x-3 px-4 py-2.5 text-sm text-gray-300 hover:bg-white/5 hover:text-white transition-colors"
                    >
                      <Edit size={16} className="text-purple-400" />
                      <span>Edit Profile</span>
                    </button>
                  </div>

                  <div className="border-t border-white/10"></div>

                  <div className="py-2">
                    <button 
                      onClick={() => { setDropdownOpen(false); localStorage.clear(); navigate('/user/login'); }}
                      className="w-full flex items-center space-x-3 px-4 py-2.5 text-sm text-red-400 hover:bg-red-500/10 transition-colors"
                    >
                      <LogOut size={16} />
                      <span>Logout</span>
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </header>

      <div className="flex">
        {/* Sidebar */}
        <aside className={`${sidebarOpen ? 'w-64' : 'w-20'} bg-[#0f172a] border-r border-white/10 min-h-screen transition-all duration-300 hidden md:block`}>
          <nav className="p-4 space-y-2">
            {navItems.map((item) => (
              <button
                key={item.id}
                onClick={() => navigate(item.path)}
                className={`w-full flex items-center space-x-3 px-4 py-3 rounded-lg transition-all ${
                  location.pathname === item.path 
                    ? 'bg-purple-600/20 text-purple-400 border border-purple-500/30' 
                    : 'text-gray-400 hover:bg-white/5 hover:text-white'
                }`}
              >
                <item.icon size={20} />
                {sidebarOpen && (
                  <>
                    <span className="flex-1 text-left font-medium">{item.label}</span>
                    {item.badge > 0 && <span className="bg-red-500 text-white text-[10px] px-1.5 py-0.5 rounded-full">{item.badge}</span>}
                  </>
                )}
              </button>
            ))}
            <button 
              onClick={() => {
                localStorage.clear();
                navigate('/user/login');
              }}
              className="w-full flex items-center space-x-3 px-4 py-3 rounded-lg text-red-400 hover:bg-red-500/10 transition-all mt-8"
            >
              <LogOut size={20} />
              {sidebarOpen && <span className="font-medium">Logout</span>}
            </button>
          </nav>
        </aside>

        {/* Main Content */}
        <main className="flex-1 p-6">
          <div className="mb-6">
            <h2 className="text-2xl font-bold text-white mb-1">REPORTS</h2>
            <p className="text-gray-400 text-sm">Analytics and reports</p>
          </div>

          {/* Report Tabs */}
          <div className="bg-[#0f172a] border border-white/10 rounded-xl p-4 mb-6 flex flex-wrap items-center justify-between gap-4">
            <div className="flex space-x-2">
              {['Daily', 'Weekly', 'Monthly'].map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-6 py-2.5 rounded-lg text-sm font-medium transition-all ${
                    activeTab === tab 
                      ? 'bg-purple-600 text-white shadow-lg shadow-purple-500/25' 
                      : 'bg-[#1e293b] text-gray-400 hover:text-white border border-white/10'
                  }`}
                >
                  {tab} Report
                </button>
              ))}
            </div>
            <div className="relative">
              <button className="flex items-center space-x-2 px-4 py-2 bg-[#1e293b] border border-white/10 rounded-lg text-sm text-gray-300 hover:text-white">
                <span>All Time</span>
                <ChevronDown size={16} />
              </button>
            </div>
          </div>

          {/* Summary Cards */}
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4 mb-6">
            {[
              { label: 'Total Alerts', value: totalAlerts, icon: AlertTriangle, color: 'text-red-400', bg: 'bg-red-500/20' },
              { label: 'Intrusions', value: intrusions, icon: Shield, color: 'text-blue-400', bg: 'bg-blue-500/20' },
              { label: 'Unknown Faces', value: unknownFaces, icon: Users, color: 'text-yellow-400', bg: 'bg-yellow-500/20' },
              { label: 'Fire Alerts', value: fireAlerts, icon: Flame, color: 'text-orange-400', bg: 'bg-orange-500/20' },
              { label: 'Crowd Alerts', value: crowdAlerts, icon: Users, color: 'text-green-400', bg: 'bg-green-500/20' },
            ].map((card, index) => (
              <div key={index} className="bg-[#0f172a] border border-white/10 rounded-xl p-4 hover:border-purple-500/30 transition-all">
                <div className="flex items-center justify-between mb-3">
                  <div className={`w-10 h-10 rounded-lg ${card.bg} flex items-center justify-center`}>
                    <card.icon className={card.color} size={20} />
                  </div>
                </div>
                <p className="text-gray-400 text-xs mb-1">{card.label}</p>
                <p className="text-2xl font-bold text-white">{card.value}</p>
              </div>
            ))}
          </div>

          {/* Charts */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
            {/* Alerts Trend */}
            <div className="bg-[#0f172a] border border-white/10 rounded-xl p-6">
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-lg font-semibold text-white">Alerts Trend</h3>
                <select className="bg-[#1e293b] border border-white/10 rounded-lg px-3 py-1.5 text-sm text-gray-300">
                  <option>All Alerts</option>
                  <option>High Priority</option>
                </select>
              </div>
              <div className="h-[250px]">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={alertData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                    <XAxis dataKey="time" stroke="#64748b" fontSize={12} tickLine={false} axisLine={false} />
                    <YAxis stroke="#64748b" fontSize={12} tickLine={false} axisLine={false} />
                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #1e293b', borderRadius: '8px' }} />
                    <Line type="monotone" dataKey="alerts" stroke="#a855f7" strokeWidth={2} dot={{ r: 3, fill: '#a855f7' }} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Threats by Type */}
            <div className="bg-[#0f172a] border border-white/10 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-white mb-6">Threats by Type</h3>
              <div className="h-[250px] flex items-center justify-center">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie data={threatData} cx="40%" cy="50%" innerRadius={60} outerRadius={90} paddingAngle={4} dataKey="value">
                      {threatData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #1e293b', borderRadius: '8px' }} />
                    <Legend 
                      layout="vertical" 
                      align="right" 
                      verticalAlign="middle"
                      formatter={(value, entry) => {
                        const item = threatData.find(t => t.name === value);
                        const pct = totalAlerts > 0 ? ((item?.value / totalAlerts) * 100).toFixed(1) : 0;
                        return <span className="text-gray-400 text-sm">{value} - {pct}%</span>;
                      }}
                    />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>

          {/* Recent Reports & Summary */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Recent Reports */}
            <div className="bg-[#0f172a] border border-white/10 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-white mb-4">Recent Reports</h3>
              {recentReports.length > 0 ? (
                <div className="space-y-3">
                  {recentReports.map((report, index) => (
                    <div key={index} className="flex items-center justify-between p-4 bg-[#1e293b] rounded-lg border border-white/5 hover:border-white/10 transition-colors">
                      <div className="flex items-center space-x-3">
                        <FileText className="text-purple-400" size={20} />
                        <div>
                          <p className="text-sm font-medium text-white">{report.title}</p>
                          <p className="text-xs text-gray-400">{report.date}</p>
                        </div>
                      </div>
                      <button className="flex items-center space-x-1 px-3 py-1.5 bg-purple-600/20 text-purple-400 rounded-lg text-xs font-medium hover:bg-purple-600/30 transition-colors">
                        <Download size={14} />
                        <span>Download</span>
                      </button>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-12">
                  <FileText className="mx-auto mb-3 text-gray-600" size={48} />
                  <p className="text-gray-400 text-sm">No reports generated yet</p>
                </div>
              )}
            </div>

            {/* Report Summary */}
            <div className="bg-[#0f172a] border border-white/10 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-white mb-4">Report Summary</h3>
              <div className="space-y-3">
                {[
                  { label: 'Total Alerts', value: totalAlerts },
                  { label: 'High Priority Alerts', value: highPriority, color: 'text-red-400' },
                  { label: 'Medium Priority Alerts', value: mediumPriority, color: 'text-yellow-400' },
                  { label: 'Low Priority Alerts', value: lowPriority, color: 'text-green-400' },
                  { label: 'Resolved Alerts', value: resolvedAlerts, color: 'text-blue-400' },
                ].map((item, index) => (
                  <div key={index} className="flex items-center justify-between p-3 bg-[#1e293b] rounded-lg border border-white/5">
                    <span className="text-sm text-gray-400">{item.label}</span>
                    <span className={`text-lg font-bold ${item.color || 'text-white'}`}>{item.value}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
};

export default Reports;